### PR TITLE
Only upload ETag and PartNumber for completeMultipartUpload

### PR DESCRIPTION
**Pull request by andylockran**
This fixes the issue #32.

According to the documentation, only the ETag and PartNumber should be part of the parts array.

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#completeMultipartUpload-property

To show this breaking, add 'ServerSideEncryption: "AES256" to your initial options - and despite it being a valid parameter, you'll see the code bum out at this point.

```
var S3 = require('aws-sdk').S3,
    S3S = require('s3-streams');

var bucket="test_bucket_for_bug_32";

var params = {
    Bucket: bucket,
    Key: "test_file.txt",
    ServerSideEncryption: "AES256"
}

var s = S3S.WriteStream(s3client, params);

s.write("Example test content.. Should probably also test with longer content..")
s.end();
```

### CODE REVIEW

**Comment by andylockran** [comment]
It's any node version older than 5 that's it's breaking for. @izaakschroeder are you happy to merge?

**Comment by izaakschroeder** [comment]
Oh. Hey @andylockran sorry for the delay. This is super great! I'm ok with blowing out old versions of node (long as we support their latest LTS which I think is 8?) and honestly I need to update a ton of stuff in this package… newer version of babel, eslint… the list is long 😆

**Comment by andylockran** [comment]
I've upgraded pretty much it all for you :)  Let me know if you'd prefer this broken out, or happy with the big leap forward :)

**Comment by izaakschroeder** [comment]
Awesome @andylockran 😄 I'm happy with a single PR, but maybe just clean up the commits a bit. I think we could rebase them to a) avoid merge commits and b) to produce a sequence of commits that all pass CI and don't represent any intermediate work. 

This also appears to update the URL to `travis/andylockran` I'm not sure if this is intentional or not and if it was your desire to manage all that.

**Pull request closed without merging**
