### PR TITLE
Revert custom E-Tags.

### PR DESCRIPTION
**Pull request by izaakschroeder**
Didn't quite work out like I'd hoped.

/cc @tonyghita

### CODE REVIEW

**Comment by izaakschroeder** [comment]
@tonyghita if you just want to do a quick check and make sure this branch fixes what you've been playing with I'll merge it after. Sorry for the delay :smile:

**Comment by izaakschroeder** [comment]
I feel like I should also include some tests that send real data to S3 instead of just mocking, as that would have caught these errors. For another PR perhaps.

**Comment by tonyghita** [comment]
Ahh this makes sense. I wasn't sure if you wanted to keep the other functionality in there so I worked around it. Thank you :)

**Comment by izaakschroeder** [comment]
No problem! Just ping me after checking that this fixes your issue and I'll merge and publish a new version on npm (and deprecate the old one).

**Comment by tonyghita** [comment]
@izaakschroeder confirmed that this version is working for me

**Comment by izaakschroeder** [comment]
Published as `s3-streams@0.2.1`. Thanks again for working through this! :tada:

**Comment by tonyghita** [comment]
:+1: :+1: my pleasure! thank you for the project

**Pull request merged**
